### ISSUE TITLE
No ToR and SEO update

### ISSUE THREAD

**Issue by MASSKAgithub** [yassine/soxy-driver#12]
So this thing seems really good but the main problem is that it uses ToR so i think this makes internet speed slower and ping higher.

For my use i only need to put a global proxy on a docker instance where normal env variables dont work. So im asking a feature where you could disable ToR by an option when running the container and make it good performance.

Also this thing i looked 3days and couldnt find, can you please add in the description keywords such as: proxy per docker container, force container using a proxy, global docker container proxy… and more like that people could find it and youll get more users.

**Comment by yassine** [comment]
You already have the possibility to choose whichever high speed socks proxy you want.
You just have to put the right parameters when creating the docker network proxying the traffic.
Configuration is done only once at the moment you'll create the network.

**Comment by yassine** [comment]
Removing tor is also removing the fallback (poka-yoke) option .
Servers go up and down an there is better fallback option than tor in terms of durability. If you configure the network with a socks proxy your TCP traffic won't go at all through TOR.
I don't believe there is room for more configurability.

**Comment by MASSKAgithub** [comment]
ok thanks for the reply, so it seems really cool thanks, i'm really happy that you continue to do a support for this project and so fast.
