### ISSUE TITLE
Make a normal HTTP option

### ISSUE THREAD

**Issue by MASSKAgithub** [yassine/soxy-driver#13]
So here you only say SOCKS5 mainly but I need http
There is http connect and other thing.

But when I use other apps with HTTP proxies I set only "http" proxy and not connect or relay, could you pls change it to make like I only just type http and it uses it as http?

**Comment by yassine** [comment]
Sorry there are no plans for this, L4 proxying is delegated to redsocks that in turn assumes proxy servers can route TCP traffic over HTTP.
