### ISSUE TITLE
http-connect | timeout error

### ISSUE THREAD

**Issue by MASSKAgithub** [yassine/soxy-driver#19]
It cant do any requests, all of time a timeout error with http-connect, my proxy works good btw. Seems like http-connect is totally broken and not working.

**Comment by yassine** [comment]
Are you sure it's http and NOT https? Most proxy providers offer only https.

**Comment by MASSKAgithub** [comment]
Ive checked with python, requests module bcs i was making a proxy checker, and the funny fact is that i cant connect to my proxy with https:// but only with http://, im 100% sure your code is broken on the http-connect and I really really need this fonctionality

**Comment by MASSKAgithub** [comment]
Im amazed how fast you replied

**Comment by yassine** [comment]
My code doesn't manage proxy connections, that logic is made at redsox
level.

**Comment by MASSKAgithub** [comment]
So what can I do to make the http-connect working? my proxy can go IP auth. its a timeout error which is reslly annoying seems like iptables is doing something wrong?

**Comment by yassine** [comment]
Is there any reason why you are preferring http over socks (knowing that
socks5 has a smaller protocol overhead)

Le sam. 25 févr. 2023 à 22:58, Yassine Echabbi ***@***.***> a
écrit :

> My code doesn't manage proxy connections, that logic is made at redsox
> level.
>

**Comment by MASSKAgithub** [comment]
i got proxies with only http that doesnt support socks this is why

**Comment by yassine** [comment]
I'm sorry for you but my code doesnt manage proxy connections. As long as
socks 5 proxies are working as you indicated in the beginning that means
that nothing is wrong with ip rules.
Iptables rules dont reach application layer at, thus the proxies different
protocols related troubles aren't at that level.

One hack would be that you run a local socks server that forwards the
traffic over a http proxy.

**Comment by MASSKAgithub** [comment]
Ok thanks!

**Comment by yassine** [comment]
I'm not 100% sure but dante socks server may support that. The idea is to
run it locally, configure it to forward traffic through the http proxy.
Then use the local address of the host as in the docker network config

Le sam. 25 févr. 2023 à 23:07, Yassine Echabbi ***@***.***> a
écrit :

> I'm sorry for you but my code doesnt manage proxy connections. As long as
> socks 5 proxies are working as you indicated in the beginning that means
> that nothing is wrong with ip rules.
> Iptables rules dont reach application layer at, thus the proxies different
> protocols related troubles aren't at that level.
>
> One hack would be that you run a local socks server that forwards the
> traffic over a http proxy.
>
>

**Comment by MASSKAgithub** [comment]
Ok thanks will try this too tomorrow,

btw is it possible to replace your redsocks by transocks?

**Comment by yassine** [comment]
Not in the near furure, im currently busy with other projects.

**Comment by MASSKAgithub** [comment]
I think I found the solution as you said with danted, so in the config file gotta do this:

for the internal adresses putting each time a different port to prevent docker network or soxy driver overlaps error
`
internal: 0.0.0.0 port=1080 
internal: 0.0.0.0 port=1081 
internal: 0.0.0.0 port=1082`
for external main ethernet adapter

then doing each time a pass block for each docker container that would be run so:

`
pass {
   from: CONTAINER_IP to: 0.0.0.0/0 port = http
   command: connect
   redirect to: PROXY_IP port = PROXY_PORT
}
   `
Here replacing each time the container_ip by the local ip that docker added to the container created on the soxy-driver network, which will be connected to a socks proxy on one of the internal adresses. the proxy_ip and proxy_port will be repoaced by the proxy ip and port so


ill try tomorrow and tell the results here

**Comment by MASSKAgithub** [comment]
Not working :/,
So ill use socks-over-http to convert my proxies

**Comment by yassine** [comment]
Make sure  you have a correctly configured danted first, without the driver
using curl or similar.
Post your config here.
I used danted a couple of years ago to tunnel through a vpn from a local
socks instance. Some configuration can be found in the soxy-chains project

**Comment by MASSKAgithub** [comment]
I've just copy pasta different parts of different websites from google and it worked! (more luck than skills lol)
The "pass" block wasn't working because it made an error which was telling that we need a license, so I've made this:


```
logoutput: syslog
user.privileged: root
user.unprivileged: nobody

internal: 0.0.0.0 port=1080

external: 192.168.0.19 # <= Here I put my local IP, bcs I was running from another pc danted that I use as a linux server
clientmethod: none
socksmethod: none


client pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0 # <= I assume that "from: 0.0.0.0/0 will be replaced by the docker container local IP"
}

socks pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0 # same assumption
}
route {
        from: 0.0.0.0/0 to: 0.0.0.0/0 via: HTTP_PROXY_IP port = HTTP_PROXY_PORT # same assumption for the: "from: 0.0.0.0/0"
        proxyprotocol: http_v1.0
        command: connect
}
```

Replacing the HTTP_PROXY_IP and HTTP_PROXY_PORT by the logical values.
Ive let the "from: 0.0.0.0/0" bcs I yet tested with 1 proxy

**Comment by MASSKAgithub** [comment]
Hmmm seems like not working on docker
Danted receives the 127.0.0.1 and not the docker container local ip

so no idea how to put a specific proxy per container

**Comment by yassine** [comment]
Only one container should be connecting to dante and that would be the
driver's container which itself is using host networking which means it
shares the network with the host.
Can you describe the topology of the various containers you setup as well
as the associated soxy networks?

**Comment by MASSKAgithub** [comment]
If I understood your question right, I'm creating the networks for the containers like that:

```docker network create -d soxy-driver PROXY_ADDRESS -o "soxy.proxyaddress"="PROXY_ADDRESS" -o "soxy.proxyport"="PROXY_PORT"```
(putting the address as the name for simplicity)

And making docker containers like that:
```docker run -d --net PROXY_ADDRESS CONTAINER_IMAGE```

Im doing that for normal socks5 proxies.


But if I use danted I'll only have 1 proxy address right, which will be at 127.0.0.1? So there is no way that I can make danted understand to which proxy forward the soxy-driver requests?

The only way that I currently found is using https://github.com/wernight/docker-dante, putting each container on a different port, like that each soxy-driver network would have different port so the containers would go to right proxies

**Comment by yassine** [comment]
If you have many http proxies the simplest solution would be to run
multiple danted instances mapping to the number of proxies you have. You
want have then to care about from where your dante incoming traffic comes
from (using a wildcard for example if that is possible).

**Comment by yassine** [comment]
* you won't*

Le lun. 27 févr. 2023 à 15:24, Yassine Echabbi ***@***.***> a
écrit :

> If you have many http proxies the simplest solution would be to run
> multiple danted instances mapping to the number of proxies you have. You
> want have then to care about from where your dante incoming traffic comes
> from (using a wildcard for example if that is possible).
>
>
>

**Comment by MASSKAgithub** [comment]
Ive found a solution!

So as told before I thaught https://github.com/wernight/docker-dante is a good idea.
and it is!

Using the same danted.conf as Ive sent before and changing only the port and proxies info each time.
I was able to make for each proxy a container with docker-dante.

THe final result was that I could access each of my http proxies separatelly by:
localhost:1080
localhost:1081
...
So now I can put each of them in different soxy-driver networks


I'm still really thankful for your help, and your REALY fast replies, (even on Discord people don't reply as fast lol).
