### ISSUE TITLE
Possibility to deny all udp traffic

### ISSUE THREAD

**Issue by ghost** [yassine/soxy-driver#4]
Hey I just wanted to quickly ask, if there is an option to disable all UDP traffic.

Kind regards

**Comment by MarcStd** [comment]
That would be very awesome. I would do a PR by myself but sadly I have no experience in GO and docker drivers.

**Comment by yassine** [comment]
Checkout the **soxy.blockUDP** option in the Readme file.
You can as well check the `.travis/functional-tests.sh` for some (documented) examples.
(Available with the 0.3.0+ version, already published to docker hub)
