### ISSUE TITLE
Make TOR optional?

### ISSUE THREAD

**Issue by markwylde** [yassine/soxy-driver#7]
Would it be easy enough to remove the tor server from soxy-driver?

Basically, I want to use soxy-driver to forward traffic in a container to a socks proxy. I don't want a fallback to tor.

I'm happy to do a PR if you can help me in the right direction? For my own testing, I just tried removing every reference to tor in the code, but I think there is something that waits for tor to start before allowing redsocks to start.

**Comment by yassine** [comment]
**Regarding the required functionality:**

Beyond being a fallback option, the tor instance is also used to route DNS requests without leaks.
If I make tor optional I have to offer an alternative for routing DNS traffic. A solution to that would be to route it through an embedded DNS server that accept TCP/UDP DNS requests and forward them to another DNS server  (8.8.8.8) through TCP only (pdnsd allows you to do just that, and offers also caching out of the box).

**Regarding your attempt to remove tor from the code:**

By removing tor references, I'm guessing that your DNS traffic is thrown away by existing IPTables rules. I think that may be an explanation for 'hanging' you're experiencing by removing the tor logic from the code.

The DNS Iptables programming is basically done [here](https://github.com/yassine/soxy-driver/blob/789973cf8cf8cbccb89c0929986d9d4bca23b429/network/network_context.go#L143)
Try to remove the DNS redirection rules and see if that solves your problem but beware that you still have define what to do with that traffic.

**Comment by markwylde** [comment]
Hi @yassine 

Thanks a lot for your reply. I actually think I wasn't getting as far as I originally thought.

I just tried building the project without making any changes, and it outputs:

```bash
1605445119.210816 notice main.c:165 main(...) redsocks started, conn_max=131072
time="2020-11-15T12:58:52Z" level=warning msg="bridge store not initialized. kv object docker/network/v1.0/bridge-endpoint/79c91c099f028aa1710d5a6954f98abde9055e02f1247de09ba7a7283c7b633f/ is not added to the store"
time="2020-11-15T12:58:52Z" level=debug msg="Received Join Request %s @ %s79c91c099f028aa1710d5a6954f98abde9055e02f1247de09ba7a7283c7b633f8f753d64cd326a5e4a689af6fde5f62384c01f8059adcecb2d636676f4c3b3b1"
time="2020-11-15T12:58:52Z" level=debug msg="Received ProgramExternalConnectivity Request"
time="2020-11-15T12:58:52Z" level=warning msg="bridge store not initialized. kv object docker/network/v1.0/bridge-endpoint/79c91c099f028aa1710d5a6954f98abde9055e02f1247de09ba7a7283c7b633f/ is not added to the store"
time="2020-11-15T12:58:52Z" level=debug msg="Received EndpointInfo Request %s @ %s79c91c099f028aa1710d5a6954f98abde9055e02f1247de09ba7a7283c7b633f8f753d64cd326a5e4a689af6fde5f62384c01f8059adcecb2d636676f4c3b3b1"
time="2020-11-15T12:58:52Z" level=debug msg="Received EndpointInfo Request %s @ %s79c91c099f028aa1710d5a6954f98abde9055e02f1247de09ba7a7283c7b633f8f753d64cd326a5e4a689af6fde5f62384c01f8059adcecb2d636676f4c3b3b1"
time="2020-11-15T12:58:58Z" level=debug msg="Received RevokeExternalConnectivity Request"
time="2020-11-15T12:58:58Z" level=debug msg="DeleteConntrackEntries purged ipv4:0, ipv6:0"
time="2020-11-15T12:58:58Z" level=warning msg="bridge store not initialized. kv object docker/network/v1.0/bridge-endpoint/79c91c099f028aa1710d5a6954f98abde9055e02f1247de09ba7a7283c7b633f/ is not added to the store"
time="2020-11-15T12:58:58Z" level=debug msg="Received Leave Request %s @ %s79c91c099f028aa1710d5a6954f98abde9055e02f1247de09ba7a7283c7b633f8f753d64cd326a5e4a689af6fde5f62384c01f8059adcecb2d636676f4c3b3b1"
time="2020-11-15T12:58:58Z" level=debug msg="Received DeleteEndpoint Request %s @ %s79c91c099f028aa1710d5a6954f98abde9055e02f1247de09ba7a7283c7b633f8f753d64cd326a5e4a689af6fde5f62384c01f8059adcecb2d636676f4c3b3b1"
time="2020-11-15T12:58:58Z" level=debug msg="bridge store not initialized. kv object docker/network/v1.0/bridge-endpoint/79c91c099f028aa1710d5a6954f98abde9055e02f1247de09ba7a7283c7b633f/ is not deleted from store"
```

But when I use the one on docker hub it works perfectly.

I think maybe the project doesn't build correctly anymore.

**Comment by yassine** [comment]
1. The output error ```curl: (6) Couldn't resolve host 'check.torproject.org' ``` indicates clearly that you're encountering a DNS resolution problem. Try to comment out the DNS redirection rule I indicated formerly.
2. I'm noticing is that you're not specifying the socks server to use when creating a network @ step 5 (See config options in the docs).
3. I'm not sure what you mean by a 'build problem'. If you're able to build the docker image using your modified code there should be no problem with the code itself from a compilation perspective.

I'd recommend you to use first the official version with your own public socks server parameters as per documentation (to make sure there is no configuration problem). 
From there, drop out the DNS iptables rules as per my original reply (To make sure you're no longer on TOR for DNS resolution). 
Finally, start dropping the remaining Tor fallback logic.

**Comment by MASSKAgithub** [comment]
did you succeed?
