### ISSUE TITLE
Restrict access to host network

### ISSUE THREAD

**Issue by slavnycoder** [yassine/soxy-driver#8]
I'm creating network with soxy-driver, and use it as network in my container.
curl https://check.torproject.org/api/ip =>  {"IsTor":true, some-tor-ip}
then i stop soxy-driver container without stopping my contanier
curl https://check.torproject.org/api/ip =>  {"IsTor":false, my PC ip}

is it possible to block the access to internet if soxy-driver is down?

**Comment by yassine** [comment]
soxy-driver acts as a decorator on top of docker's bridge driver. It offers the same set capabilities in terms of functionality unless for outgoing TCP traffic.
The natural behavior of a decorator that is dropped is it to leave the decorated component behavior intact. Plus, it is natural for the driver to clean after itself if it is stopped (by removing isolation rules).

That leaves you with two choices:

1. Not stopping the driver.

2. Create a fork and build a custom driver that fulfills your esoteric needs. The iptables clean-up logic happens [here](https://github.com/yassine/soxy-driver/blob/789973cf8cf8cbccb89c0929986d9d4bca23b429/driver/driver.go#L249). If you drop that line the outgoing Internet traffic will be dropped, but your `iptables` tables would be left in a 'dirty' state.
